ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:github-pages-uri: https://dlmiles.github.io/gradle-xjc-plugin
:github-uri: https://github.com/dlmiles/gradle-xjc-plugin
:github-m2-uri: https://maven.pkg.github.com/dlmiles/gradle-xjc-plugin
:maven-groupId: io.github.dlmiles
:uri-build-status: https://github.com/dlmiles/gradle-xjc-plugin/actions/workflows/build.yml
:img-build-status: https://github.com/dlmiles/gradle-xjc-plugin/actions/workflows/build.yml/badge.svg

ifdef::env-github[]
image:{img-build-status}[CI-Gradle-build,link={uri-build-status}]
#CI Targets: `Java 8` and `Java 11` with `Gradle 5.6` through `Gradle 8.0.2`#
endif::[]

= Gradle XJC Plugin

Invokes the `xjc` binding compiler from a Gradle build.


== Features

- Automatically enable XJC code generation for each source set in your project
- support different versions of XJC through classpath isolation
- producing and consuming episodes
- catalogs with `maven:` and `classpath:` URI resolution (similar to maven-jaxb2-plugin)


== Requirements

The Gradle plugin itself:

- Gradle 5.6 or higher
- JDK 1.8 or higher (when running Gradle)

The XJC Tool requirements:

- If using XJC Tool 4.x or later, the XJC Tool requires JDK 11 or higher while this
  plugin only requires 1.8 or higher, earlier versions of XJC Tool are
  compatible with JDK 1.8
- Some specific XJC Tool versions may have been published with incorrect byte code
  compatibility, resulting in those versions not running on the Java SE version they
  intended to target
- See section link:{github-pages-uri}#_xjc_tool_runtime_java_compatibility[XJC Tool Runtime Java Compatibility]


== Quick Start

Apply the `org.unbroken-dome.xjc` plugin to your Gradle build script and add an appropriate
dependency on the JAXB API:

ifdef::env-github[]
[source,kotlin,subs="attributes+"]
.settings.gradle(.kts)
----
pluginManagement {
    // 3rd party releases and SNAPSHOTs
    maven {
        url "{github-pages-uri}/java8/maven2"
        // url "{github-m2-uri}"
        content {
            // this repository *only* contains artifacts for specific groups
            includeGroup "org.unbroken-dome.xjc"
            includeGroup "org.unbroken-dome.gradle-plugins"
ifdef::env-github[]

            includeGroup "{maven-groupId}.xjc"
            includeGroup "{maven-groupId}.gradle-plugins"
endif::[]
        }
    }

    // Official releases only
    gradlePluginPortal()   
}
----

endif::[]
[source,kotlin]
.build.gradle(.kts)
----
plugins {
    id("org.unbroken-dome.xjc") version "2.1.0-SNAPSHOT"
}

dependencies {
    implementation("javax.xml.bind:jaxb-api:2.3.0")
}
----

Put your schemas (`.xsd`), binding customization files (`.xjb`) and catalogs (`.cat`)
into `src/main/schema`.

That's it! The plugin will automatically invoke XJC to generate code from your schemas and include
it the `main` Java compilation.


== Further Documentation

* {github-pages-uri}/[User Manual]
* {github-pages-uri}/dokka/gradle-xjc-plugin/[API/DSL Documentation]
* {github-m2-uri}/[Github Maven2 Package Browse]
* {github-pages-uri}/java8/maven2/[Github-Pages Maven2 Artifact Browse]
* {github-pages-uri}/artifacts/[Maven2 Artifact Archive Download]

* {github-pages-uri}/java8/tests/[Java 8 Test Reports]
* {github-pages-uri}/java11/tests/[Java 11 Test Reports]
