= XJC Versions

XJC has been around for a long time and comes in a variety of versions, including standard versions provided by
Oracle and non-standard forks from third parties. They should usually correspond with the version of the JAXB
API / runtime used, but it is also possible to use a newer XJC to generate code for use with an earlier JAXB target.

The `org.unbroken-dome.xjc` plugin supports the standard XJC versions 2.2, 2.3, 2.4 and 3.0. Other versions may work
as well but are not tested. The plugin will use XJC 2.3 by default if the version is not specified.

NOTE: XJC 3.0 is currently in milestone status but since the interface to XJC has not
really changed over the years, it should be safe to consider it stable. Nevertheless, the plugin will use XJC 2.3
as default until version 3.0 is released.


== Selecting an XJC Version

The easiest way to select an XJC version is to use the property `xjcVersion` on the global `xjc` extension.
The value should be one of the supported versions. This is a global setting because it is assumed that the
same XJC version will be used for each source set.

For example, to use XJC 3.0:

[source,groovy,role="primary"]
.Groovy
----
xjc {
    xjcVersion = '3.0'
}
----

[source,kotlin,role="secondary"]
.Kotlin
----
xjc {
    xjcVersion.set("3.0")
}
----

TIP: When changing the XJC version, remember to also use an appropriate version of the JAXB API in your
dependencies. The plugin doesn't do this.

Changing the version with the `xjcVersion` property will effectively change the classpath that is used for
invoking XJC, with the following dependencies:

[cols="1,4"]
|===
| XJC Version | Classpath artifacts

| 2.2
| `com.sun.xml.bind:jaxb-xjc:2.2.11`
  `com.sun.xml.bind:jaxb-core:2.2.11`
  `com.sun.xml.bind:jaxb-impl:2.2.11`
  `javax.xml.bind:jaxb-api:2.2.11`

| 2.3
| `com.sun.xml.bind:jaxb-xjc:2.3.3`

| 2.4
| `com.sun.xml.bind:jaxb-xjc:2.4.0-b180830.0438`
  `com.sun.xml.bind:jaxb-core:2.3.0.1`
  `com.sun.xml.bind:jaxb-impl:2.4.0-b180830.0438`
  `javax.xml.bind:jaxb-api:2.4.0-b180830.0359`

| 3.0
| `com.sun.xml.bind:jaxb-xjc:3.0.2`
  `com.sun.xml.bind:jaxb-core:3.0.2`
  `com.sun.xml.bind:jaxb-impl:3.0.2`
  `jakarta.xml.bind:jakarta.xml.bind-api:3.0.1`

|===


== Setting the XJC Tool Classpath Explicitly

You can also manually configure the classpath for invoking XJC by adding dependencies
to the `xjcTool` configuration. As soon as this configuration contains any dependencies,
the defaults will back away, and the `xjc.xjcVersion` property will have no effect.

You should specify at least `jaxb-xjc` it is possible its dependencies are included
transitively or you can include them with additional `xjcTool` directives.

For example:

[source,groovy,role="primary"]
.Groovy
----
dependencies {
    xjcTool 'com.sun.xml.bind:jaxb-xjc:3.0.2'
    // Optional explicit version set:
    xjcTool 'com.sun.xml.bind:jaxb-core:3.0.2'
    xjcTool 'com.sun.xml.bind:jaxb-impl:3.0.2'
    xjcTool 'jakarta.xml.bind:jakarta.xml.bind-api:3.0.1'
}
----

[source,kotlin,role="secondary"]
.Kotlin
----
dependencies {
    "xjcTool"("com.sun.xml.bind:jaxb-xjc:3.0.2")
    // Optional explicit version set:
    "xjcTool"("com.sun.xml.bind:jaxb-core:3.0.2")
    "xjcTool"("com.sun.xml.bind:jaxb-impl:3.0.2")
    "xjcTool"("jakarta.xml.bind:jakarta.xml.bind-api:3.0.1")
}
----
